# Generated by Django 5.0.6 on 2024-05-22 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300, verbose_name='action')),
                ('place', models.CharField(max_length=50, verbose_name='place of action')),
                ('time', models.DateTimeField(verbose_name='time of action')),
                ('is_good', models.BooleanField(default=False, verbose_name='is good habit')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='reward after completed action')),
                ('period', models.PositiveIntegerField(blank=True, null=True, verbose_name='periodicity of habit')),
                ('time_to_complete', models.PositiveIntegerField(blank=True, null=True, verbose_name='time to complete action')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='related habit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
